<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_Pytorch/blob/main/Model/Transformer_Chatbot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 마련

In [1]:
import pandas as pd

In [2]:
ls

drive/  sample_data/


In [3]:
cd drive/MyDrive/Pytorch\ NLP/data_in/Chatbot

/content/drive/MyDrive/Pytorch NLP/data_in/Chatbot


In [4]:
ls

2_Fine_ChatbotData.csv  ChatbotData.csv       Mecab-ko-for-Google-Colab/
best_weight/            Fine_ChatbotData.csv  vocab_word.csv


In [5]:
vocab_word=pd.read_csv('vocab_word.csv')
train_data=pd.read_csv('2_Fine_ChatbotData.csv')

In [10]:
BATCH_SIZE = 2
MAX_LEN = 25
EPOCHS = 30
NUM_LAYERS = 2
FEED_WORWARD_DIM=2048

In [7]:
pip install torchtext==0.6

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 55.6 MB/s eta 0:00:00
  Attempting uninstall: torchtext
    Found existing installation: torchtext 0.15.2
    Uninstalling torchtext-0.15.2:
      Successfully uninstalled torchtext-0.15.2


In [8]:
from torchtext import data

In [11]:
# vocab 전용
V=data.Field(sequential=True,
             use_vocab=True,
             tokenize=str.split,
             init_token='<sos>',
             eos_token='<eos>',
             fix_length=MAX_LEN)

In [12]:
Q=data.Field(sequential=True,
             use_vocab=True,
             tokenize=str.split,
             batch_first=True,
             fix_length=MAX_LEN)

A=data.Field(sequential=True,
             use_vocab=True,
             init_token='<sos>',
             eos_token='<eos>',
             tokenize=str.split,
             batch_first=True,
             fix_length=MAX_LEN)
LABEL=data.Field(sequential=True,
                 use_vocab=True,
                 eos_token='<eos>',
                 tokenize=str.split,
                 batch_first=True,
                 fix_length=MAX_LEN)

In [13]:
from torchtext.data import TabularDataset

In [14]:
train_data=TabularDataset('2_Fine_ChatbotData.csv',format='csv',fields=[('question',Q),('answer',A),('label',LABEL)],skip_header=True)
vars(train_data[0])

{'question': ['12시', '땡'],
 'answer': ['하루가', '또', '가네요'],
 'label': ['하루가', '또', '가네요']}

In [15]:
vocab_data=TabularDataset('vocab_word.csv',format='csv',fields=[('vocab_word',V)],skip_header=True)

In [16]:
V.build_vocab(vocab_data,min_freq=2)

Q.vocab=V.vocab
A.vocab=V.vocab
LABEL.vocab=V.vocab

In [17]:
import random
import torch
SEED=123
random.seed(SEED)
torch.manual_seed(SEED)

train_data,val_data=train_data.split(split_ratio=0.9,random_state=random.seed(SEED))

In [18]:
from torchtext.data import Iterator

In [19]:
train_iter=Iterator(train_data,batch_size=BATCH_SIZE)
val_iter=Iterator(val_data,batch_size=BATCH_SIZE)

In [20]:
batch=next(iter(train_iter))
batch.question

tensor([[ 742,  202, 1854, 5302,  211,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1],
        [  45,    0,    0, 2612,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1]])

In [21]:
batch.answer

tensor([[   2, 4448, 4528, 3233,  858,  321, 4934,   89,    3,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1],
        [   2,  978, 1768,  539,   89,    3,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1]])

In [22]:
batch.label

tensor([[4448, 4528, 3233,  858,  321, 4934,   89,    3,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1],
        [ 978, 1768,  539,   89,    3,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1]])

In [23]:
train_iter=Iterator(train_data,batch_size=BATCH_SIZE)
val_iter=Iterator(val_data,batch_size=BATCH_SIZE)

# 모델 구현

In [28]:
## hyperparameter
BATCH_SIZE=2
EPOCH=30
MAX_LEN=25
kargs={'max_len':MAX_LEN,
       'emb_dim':512,
       'num_layers':2,
       'num_heads':6,
       'ffn_dim':2048,
       'vocab_size':len(V.vocab)
       }

device='cuda' if torch.cuda.is_available() else 'cpu'

In [25]:
import torch
import torch.nn as nn

In [ ]:
class EncoderLayer(nn.Module):
  def __init__(self,**kargs)

In [ ]:
class Encoder(nn.Module):
  